"""add foreclosure fields

Revision ID: 68faa821de7d
Revises: 44384c17e98c
Create Date: 2026-08-21 10:55:18.607209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68faa821de7d'
down_revision: Union[str, Sequence[str], None] = '44384c17e98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('auction_date', sa.Date(), nullable=True))
    op.add_column('properties', sa.Column('foreclosure_status', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('opening_bid', sa.Numeric(), nullable=True))
    op.add_column('properties', sa.Column('estimated_value', sa.Numeric(), nullable=True))
    op.add_column('properties', sa.Column('property_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'property_type')
    op.drop_column('properties', 'estimated_value')
    op.drop_column('properties', 'opening_bid')
    op.drop_column('properties', 'foreclosure_status')
    op.drop_column('properties', 'auction_date')
    # ### end Alembic commands ###
