"""add market comparables

Revision ID: 743e1bfca616
Revises: 8b9164e18be1
Create Date: 2026-09-30 18:55:46.889420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743e1bfca616'
down_revision: Union[str, Sequence[str], None] = '8b9164e18be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_comparables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('area_sqft', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Numeric(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_comparables')
    # ### end Alembic commands ###
