"""add property and comparable location

Revision ID: 75d2bf462605
Revises: 743e1bfca616
Create Date: 2026-10-01 04:56:17.420004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d2bf462605'
down_revision: Union[str, Sequence[str], None] = '743e1bfca616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('city', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('locality', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'locality')
    op.drop_column('properties', 'city')
    # ### end Alembic commands ###
