"""add property valuations

Revision ID: 8b9164e18be1
Revises: 1b7efcfba5ad
Create Date: 2026-09-29 18:55:48.384512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9164e18be1'
down_revision: Union[str, Sequence[str], None] = '1b7efcfba5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('estimated_value', sa.Numeric(), nullable=False),
    sa.Column('valuation_method', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_valuations_property_id'), 'property_valuations', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_valuations_property_id'), table_name='property_valuations')
    op.drop_table('property_valuations')
    # ### end Alembic commands ###
